apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: gaurav2203/microservice-backend:v2
        name: microservice-backend
        imagePullPolicy: Always
        env: 
          - name: DATABASE_URL
            value: "postgresql://user:password@database:5432/mydb"
        ports: 
          - containerPort: 5001

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
spec:
  ports:
  - name: backend
    port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: backend
  type: ClusterIP
